plugin: axis.appmgmt.cam_scan_plugin  # Name of the plugin
group_name: cameras                   # Name of the group to add hosts to
num_of_threads: 50                    # Nbr of threads to use for the scanning, one thread per IP will be used for scanning
subnets_to_scan:                      # A list of subnets to scan in CIDR format e.g. '- 172.27.67.0/28'
  # CAMNET
  # - 172.25.71.168
  # - 172.25.70.0/24

  # AMT POOL
  # - 172.27.52.150
  # - 172.27.67.242
  # - 172.27.72.105
  # - 172.27.72.116
  # - 172.27.72.212

  # HOME NETWORK
  - 192.168.5.0/24

# Note! Any changes to the filter will not take effect an already cached inventory.
# To refresh the inventory before the cache_timeout has expired, either remove the cache
# from the location pointed out in cache_connection, or add the following task to the playbook:
# - name: Refresh the inventory, whether cached or not
#   meta: refresh_inventory
# IN ADDITION: Filtering of devices is only possible for devices using default credentials
filter:                               # Optional
  acap4_support: true
#  fw_min: 9                             # Optional, if set only hosts running this fw version or higher ones will be added
#  fw_max: 10.11.15                            # Optional, if set only hosts running this fw version or lower ones will be added
#  hw_id:  802                            # Optional, if set only hosts with this exact hw_id will be added

cache: false
cache_plugin: jsonfile
cache_timeout: 100
cache_connection: /tmp/axis_inventory
